[tox]
envlist = py310,py311,py312,py313,py314
requires = tox-uv

[testenv]
dependency_groups = dev
commands =
	pytest --cov=face --cov-report=xml:.tox/coverage-{envname}.xml {posargs} face/test/

[testenv:coverage-report]
dependency_groups = dev
commands =
	coverage combine
	coverage xml -o .tox/coverage.xml
	coverage report
	coverage html -d htmlcov
